name: multistreamer_pomodoro
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  twitch_manager:
    path: ./plugins/twitch_manager
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  url_launcher: ^6.1.14
  enhanced_containers:
    path: ./plugins/enhanced_containers
  provider: ^6.0.5
  firebase_core: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BebasNeue
      fonts:
      - asset: assets/fonts/BebasNeue-Regular.otf
      - asset: assets/fonts/BebasNeue-Bold.otf
        weight: 700
    - family: Nirmala
      fonts:
      - asset: assets/fonts/Nirmala-Regular.ttf
